### ISSUE TITLE
[PE-D][Tester D] Error Message does not display person index correctly in deleteMeeting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-1/tp#230] opened 2024-04-05 21:22 UTC
When an invalid person index is used for the `deleteMeeting` command, The error message does not display the client index correctly but instead displays `%1$d`.

Expected: "... person index 100..."
Actual: "... person index %1$d`..."

Steps to reproduce:
1. execute : `deleteMeeting clientIndex/100 meetingIndex/1` [NOTE that 100 is an index that is out of bounds. any positive index that is out of bounds seems to produce the same error.]

![image.png](https://raw.githubusercontent.com/ZhiWei1010/ped/main/files/6a61dd32-b53a-43e0-96e3-0a26a83146c4.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: ZhiWei1010/ped#13

**Comment by itstrueitstrueitsrealitsreal** [comment] 2024-04-06 07:04
Duplicate of #170

**Closed as completed by itstrueitstrueitsrealitsreal** 2024-04-06 07:04 UTC
Labels: type.FunctionalityBug, type.Duplicate
