### ISSUE TITLE
[PE-D][Tester D] Different prefix used to specify description of meeting

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F08-1/tp#243] opened 2024-04-05 21:36 UTC
For addMeeting, the prefix used to specify description is `d/`.

For editMeeting the prefix used to specify description is `n/`.

Could consider standardising this to avoid confusion for users, optimising user experience!

![image.png](https://raw.githubusercontent.com/ZhiWei1010/ped/main/files/4c812b7b-7296-420b-8247-6174472290b8.png)

![image.png](https://raw.githubusercontent.com/ZhiWei1010/ped/main/files/f99f08fa-3a33-40ab-a419-a618a26a1a13.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: ZhiWei1010/ped#24

**Comment by itstrueitstrueitsrealitsreal** [comment] 2024-04-06 07:38
Duplicate of #192

**Closed as completed by itstrueitstrueitsrealitsreal** 2024-04-06 07:38 UTC
Labels: type.FeatureFlaw, type.Duplicate
