### ISSUE TITLE
[PE-D][Tester D] command `exit` not found in command summary of User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F08-1/tp#172] opened 2024-04-05 17:10 UTC
Command `exit` is missing from the command summary in the User Guide

![image.png](https://raw.githubusercontent.com/ZhiWei1010/ped/main/files/9cc61288-afc9-43ee-9a2e-10ef2466da34.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ZhiWei1010/ped#3

**Comment by itstrueitstrueitsrealitsreal** [comment] 2024-04-08 12:33
Duplicate of #166

**Closed as completed by itstrueitstrueitsrealitsreal** 2024-04-08 12:33 UTC
Labels: type.DocumentationBug, type.Duplicate
